// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wiisportsresort/chat/server/ent/predicate"
	"github.com/wiisportsresort/chat/server/ent/privatemessage"
)

// PrivateMessageDelete is the builder for deleting a PrivateMessage entity.
type PrivateMessageDelete struct {
	config
	hooks    []Hook
	mutation *PrivateMessageMutation
}

// Where appends a list predicates to the PrivateMessageDelete builder.
func (pmd *PrivateMessageDelete) Where(ps ...predicate.PrivateMessage) *PrivateMessageDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *PrivateMessageDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pmd.hooks) == 0 {
		affected, err = pmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrivateMessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pmd.mutation = mutation
			affected, err = pmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pmd.hooks) - 1; i >= 0; i-- {
			if pmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *PrivateMessageDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *PrivateMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: privatemessage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: privatemessage.FieldID,
			},
		},
	}
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
}

// PrivateMessageDeleteOne is the builder for deleting a single PrivateMessage entity.
type PrivateMessageDeleteOne struct {
	pmd *PrivateMessageDelete
}

// Exec executes the deletion query.
func (pmdo *PrivateMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{privatemessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *PrivateMessageDeleteOne) ExecX(ctx context.Context) {
	pmdo.pmd.ExecX(ctx)
}
